### PR TITLE
Recover from panic after processing single key

### PR DESCRIPTION
**Pull request by kopper**

### CODE REVIEW

**Review by ash2k — CHANGES_REQUESTED** [review]
Why is this needed?
Panics are caused by bugs in code. The only correct way to respond to a bug is to stop program execution ASAP. Otherwise the program may keep corrupting state and giving invalid results.

**Comment by kopper** [comment]
This is needed to limit blast radius. We shouldn't stop processing all items if there is one bad apple (or poison pill). This is common practice. You don't crash web server if processing single request fails because of internal error.

**Comment by ash2k** [comment]
The problem is we don't know what have gone wrong. By definition panic is when you cannot recover, cannot just return an error. This stuff is part of a controller which runs on kube. Kube will restart it, it is fine. Also we'll get an alert. If we merge this, we'll need to monitor logs for this message and then alert people. And restart the instance anyway because it might have corrupted state in memory.

**Comment by kopper** [comment]
> Kube will restart it, it is fine.

Well, Kube will restart it and it will die soon after again.

> panic is when you cannot recover

You can't recover for this item. That is why we are dropping it out of the queue. I might be wrong but I assumed that it won't be processed again after that.

> If we merge this, we'll need to monitor logs for this message and then alert people

Yes. We could use proper metrics somehow, for example by providing ability to register listener that decides what to do with the recovered failure?

> The problem is we don't know what have gone wrong.

My intent is to stop processing and log the error, whatever has been corrupted I don't intend to corrupt more. At the same time I don't want to stop the world because we can't process one or few items.

**Comment by ash2k** [comment]
You are assuming that it is this item that have caused the panic. It may be something else that will keep causing panics for all items. You just cannot know.

>> If we merge this, we'll need to monitor logs for this message and then alert people

> Yes. We could use proper metrics somehow, for example by providing ability to register listener that decides what to do with the recovered failure?

I was trying to say that status quo does not require any additional monitoring i.e. less work for us.

**Comment by kopper** [comment]
> You are assuming that it is this item that have caused the panic. It may be something else that will keep causing panics for all items.

What do you mean? What else could it be except some RuntimeErrors?

> I was trying to say that status quo does not require any additional monitoring

I'm pretty sure any production system will have to monitor for "Dropping object out of the queue" failures anyway. The only thing I did is converting panic errors to regular errors.

**Comment by kopper** [comment]
@ash2k Can I merge this?

**Comment by ash2k** [comment]
> What do you mean? What else could it be except some RuntimeErrors?

- Some RuntimeErrors - bugs in our code
- Bugs in libraries we use
- Bugs in Go compiler: check the bug tracker
- Bugs in Go runtime: check the bug tracker
- Bugs in OS kernel: thousands of them :)
- Bugs in hardware
- Bugs in firmware
- Bugs in CPU: see the [errata section](https://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/xeon-e5-family-spec-update.pdf). Just a random link google gave me. More links: https://danluu.com/cpu-bugs/ and https://wiki.osdev.org/CPU_Bugs
- Errors due to external conditions - dust, jumping current/voltage, bugs (literally i.e. insects), cosmic rays (this is not a joke 😄). Lots of things that can corrupt state in RAM.
- Hardware getting old and malfunctioning. Especially capacitors, but silicon as well.
- ...

Most of the code is not written to deal with things that "cannot happen" (i.e. this pointer cannot be nil because I have just checked... but then it is) because it is impossible to code against that. And of course you cannot handle such stuff in the program because you cannot possibly know what went wrong. The only correct thing to do is to stop. Otherwise the program might become a zombie that cannot function as a healthy organism but also does not die. It can make attempts to function but be corrupting data instead of properly handling it.
It is safer to stop, especially for a kube controller.

**Comment by kopper** [comment]
OK, I'll decline this PR for now and possibly will come with whitelist of specific panics to recover from.

**Pull request closed without merging**
